### ISSUE TITLE
Universal binary for macOS

### ISSUE THREAD

**Issue by wezm** [keyboardio/focus-send#3]
Instead of separate x86 and arm binaries for macOS it would be nicer for end users to publish a universal binary that works with both, as it typically done for GUI apps.

Most of the pieces are already in place in CI. Instead of creating two tar archives `lipo` should be used to create the universal binary, and that should be published as a single tar archive. See an example of this in one of my projects:

https://github.com/wezm/rsspls/blob/155cdf6c56fb2aa84fc975db1e6fe073ae57f70b/.cirrus.yml#L79

If I get a moment over the weekend I might open a PR.

**Comment by algernon** [comment]
I've been wondering how to do an universal package, but didn't get around to research it. Now I won't have to look, thanks for the pointer! It looks simple enough, so I might try my hands on it too, unless you want to submit a PR, in which case I'll sit back and just merge. =)
